--SQL CLAUSES

--ORDER CLAUSE IS BY DEFAUT SET TO ASCENDING ORDER, SET DESC FOR DESCENDING ORDER
SELECT * FROM EMP ORDER BY SAL DESC

--USING MULTIPLE PARAMETERS WITH ORDER CLAUSE
SELECT * FROM EMP ORDER BY SAL,ENAME

--USING COUNT AND GROUP BY CLAUSE TO COUNT THE NO OF EMP IN EACH DEPT 
SELECT DEPTNO, COUNT (DEPTNO) EMPCOUNT FROM EMP GROUP BY DEPTNO

--USING COUNT, GROUP BY AND HAVING CLAUSE TO COUNT THE NO OF EMP IN DEPT NO 30
SELECT DEPTNO, COUNT (DEPTNO) EMPCOUNT FROM EMP
WHERE DEPTNO = 30 GROUP BY DEPTNO HAVING COUNT (DEPTNO) >= 4

SELECT JOB, SUM(SAL) AS TOTAL FROM EMP GROUP BY JOB HAVING SUM(SAL) >= 3000

SELECT TOP(5) * FROM EMP
SELECT TOP(50) PERCENT * FROM EMP

--CASE STATEMENTS
SELECT *, CASE WHEN SAL BETWEEN 700 AND 1500 THEN 'LOW_SAL'
WHEN SAL BETWEEN 1600 AND 2500 THEN 'AVG_SAL'
ELSE 'HIGH_SAL' END AS SAL_GRADE FROM EMP