USE PGA48 --USE THE (USE DB_NAME) COMMAND TO MAKE SURE THE TABLE IS CREATED IN THAT PARTICULAR TABLE ONLY

--TO CREATE A TABLE
CREATE TABLE CUSTOMER(
CID INT,
CNAME CHAR (10),
CADD VARCHAR (100))

--THIS IS A SINGLE LINE COMMENT USING (--)
/*THIS IS A
MULTI LINE
COMMENT USING (/*...*/)*/

--TO KNOW THE STRUCTURE OF THE TABLE, USE SP_HELP COMMAND
SP_HELP CUSTOMER

INSERT INTO CUSTOMER(CID, CNAME, CADD, CPH_NO) VALUES (600, 'tom', 'NAGPUR', 102938)
INSERT INTO CUSTOMER VALUES (200, 'JACK', 'DELHI', 234567)

SELECT * FROM CUSTOMER --TO SELECT THE ENTIRE TABLE, USE *
SELECT CID, CNAME FROM CUSTOMER --TO SELECT SPECIFIC COLUMNS, USE COLUMN NAMES

--TO INSERT INTO SPECIFIC COLUMNS, USE COLUMN NAMES
INSERT INTO CUSTOMER (CID, CNAME) VALUES (300, 'JAMES')

--INSERTING MULTIPLE ROWS OF DATA
INSERT INTO CUSTOMER VALUES (400, 'KATE', 'UK', 345678), (500, 'XYZ', 'USA', 456789)

--ADDING COLUMNS TO THE TABLE
ALTER TABLE CUSTOMER ADD CPH_NO INT 
ALTER TABLE CUSTOMER ADD CGEN VARCHAR(10)

--CHANGING THE DATA TYPE OF A COLUMN
ALTER TABLE CUSTOMER ALTER COLUMN CPH_NO BIGINT

--TO DROP/DELETE A COLUMN
ALTER TABLE CUSTOMER DROP COLUMN CGEN

--UPDATING EXISTING ROWS
UPDATE CUSTOMER SET CPH_NO = 567890 WHERE CID = 300
UPDATE CUSTOMER SET CPH_NO = 654321 WHERE CID = 200

--DELETING ROWS/RECORDS FROM THE TABLE
DELETE FROM CUSTOMER WHERE CID = 100 --SINGLE ROW
DELETE FROM CUSTOMER --ALL THE ROWS

--COPY OF A TABLE
SELECT * INTO NEWTABLE FROM CUSTOMER

--ALTERNATIVE OF COPY COMMAND
SELECT * INTO WITHDATA FROM CUSTOMER WHERE 1=1

--COPY THE TABLE STRUCTURE ONLY AND NOT THE DATA
SELECT * INTO NODATA FROM CUSTOMER WHERE 1=0

SELECT * FROM NEWTABLE
SELECT * FROM WITHDATA
SELECT * FROM NODATA

--ALIAS FOR COLUMNS WHILE PRESENTING THE TABLE
SELECT CID AS CUSTOMER_ID, CNAME "CUSTOMER NAME", CADD CUSTOMER_ADDRESS FROM CUSTOMER

--DATA TYPES (MEMORY, DATE) *APPLICABLE FOR SQL SERVER ONLY
CREATE TABLE SAMPLE (SALARY MONEY, DOB DATE)
INSERT INTO SAMPLE VALUES (1000, '06-26-2025')

--DEFUALT DATE DATA TYPE INPUT FORMAT MM-DD-YYYY
--DEFAULT DATE DATA TYPE OUTPUT FORMAT YYYY-MM-DD

SELECT * FROM SAMPLE

--IDENTITY COLUMN (SEQUENCE)
--SYNTAX: COLUMN_NAME DATA_TYPE IDENTITY(START_VALUE, INCREMENT)
CREATE TABLE TEST (SL_NO INT IDENTITY(100, 1), NAME CHAR(10))
INSERT INTO TEST (NAME) VALUES ('TOM'),('JAMES'),('JACK') 

SELECT * FROM TEST

ALTER TABLE CUSTOMER ALTER COLUMN CPH_NO TINYINT

CREATE TABLE EXT (PH INT)
INSERT INTO EXT VALUES (12345678)

ALTER TABLE EXT ALTER COLUMN PH CHAR(10)

SELECT * FROM CUSTOMER WHERE CNAME = 'TOM'

ALTER TABLE CUSTOMER ADD ID INT IDENTITY (1,1)

