--Assignment on DDL,DML

--1.CREATE A TABLE ORDERS WITH NECESSARY FIELDS (ORDER_ID,ORDER_NAME,ORDER_DETAILS ETC)WITH DATATYPES.

CREATE TABLE ORDERS (ORDER_ID INT IDENTITY(1,1), ORDER_NAME VARCHAR(20), ORDER_DETAILS VARCHAR(50), ORDER_VALUE INT)

--2. ADD ATLEAST 10 RECORDS TO THE CREATED TABLE.
INSERT INTO ORDERS(ORDER_NAME, ORDER_DETAILS, ORDER_VALUE) VALUES ('BOTTLE','BAILLEY',20),
('PHONE', 'POCO', 30000),
('WATCH', 'TITAN', 1000),
('MOUSE', 'ZEB', 250),
('LAPTOP', 'LOQ', 80000),
('AC', 'LG', 40000),
('SHOES', 'WOODLAND', 2000),
('FAN', 'USHA',1200),
('NOTEBOOK', 'CLASSMATE', 40),
('PEN', 'RORITO', 10)

--3. ADD COLUMN(NEW_COLUMN) TO THE ORDER TABLE.
ALTER TABLE ORDERS ADD SALES INT

--4. MODIFY THE EXISTING DATATYPE FOR THE NEWLY CREATED COLUMNS(EX : INT TO BIGINT /CHAR TO VARCHAR).
ALTER TABLE ORDERS ALTER COLUMN SALES BIGINT

--5. DISPLAY THE COMPLETE TABLE DATA.
SELECT * FROM ORDERS

--6. DISPLAY ONLY FEW COLUMNS FROM THE TABLE.
SELECT ORDER_ID, ORDER_NAME FROM ORDERS

--7. UPDATE VALUES FROM ORDER TABLE WHOSE ORDER_ID IS 10.
UPDATE ORDERS SET ORDER_DETAILS = 'CELLO' WHERE ORDER_ID = 10

--8. DELETE ORDER_ID WHOSE ORDER VALUES IS LESS THAN 100.
DELETE FROM ORDERS WHERE ORDER_VALUE<100

--9. Create table product with column name as Prod_id and insert unique sequential values.
CREATE TABLE PRODUCT (Prod_id INT IDENTITY(100,1))
